export const mockData = {
	data: {
		exhaustive: {
			nbHits: false,
			typo: true,
		},
		exhaustiveNbHits: false,
		exhaustiveTypo: true,
		hits: [
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'miika_raitakari',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Improving the lives of short-term rental hosts',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://botvisor.ai',
					},
				},
				_tags: ['story', 'author_miika_raitakari', 'story_38851468'],
				author: 'miika_raitakari',
				children: [38851469],
				created_at: '2024-01-03T06:54:31Z',
				created_at_i: 1704264871,
				num_comments: 1,
				objectID: '38851468',
				points: 1,
				story_id: 38851468,
				title: 'Improving the lives of short-term rental hosts',
				updated_at: '2024-01-03T06:54:39Z',
				url: 'https://botvisor.ai',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'keyurraval18',
					},
					story_text: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							"Hey HN,<p>The journey from a SaaS idea to a working prototype can be a long, winding road. My partner Shyam and I, with years of startup experience under our belts, have faced this repeatedly. We struggled with building a foundation for our projects - it's daunting and takes your focus away from what truly matters, your brilliant ideas.<p>To bridge this gap, we've cooked up something that we're thrilled to share with you today - SaaSKits.<p>SaaSKits is a simple, efficient boilerplate to kickstart your SaaS ideas. It's built using Remix, Stripe, Prisma, and Resend, designed to free you from the nitty-gritty of setting up a project, so you can get straight to building your product.<p>No more stress over starting from scratch. No more wasting days on initial codebases. Just your ideas, accelerated with SaaSKits.<p>We look forward to your feedback, and can't wait to see what you build with SaaSKits!<p>To quicker launches and big dreams,\nKeyur",
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Show HN: The fastest way to build your SaaS',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://saaskits.dev',
					},
				},
				_tags: ['story', 'author_keyurraval18', 'story_38851467', 'show_hn'],
				author: 'keyurraval18',
				created_at: '2024-01-03T06:54:07Z',
				created_at_i: 1704264847,
				num_comments: 0,
				objectID: '38851467',
				points: 1,
				story_id: 38851467,
				story_text:
					'Hey HN,<p>The journey from a SaaS idea to a working prototype can be a long, winding road. My partner Shyam and I, with years of startup experience under our belts, have faced this repeatedly. We struggled with building a foundation for our projects - it&#x27;s daunting and takes your focus away from what truly matters, your brilliant ideas.<p>To bridge this gap, we&#x27;ve cooked up something that we&#x27;re thrilled to share with you today - SaaSKits.<p>SaaSKits is a simple, efficient boilerplate to kickstart your SaaS ideas. It&#x27;s built using Remix, Stripe, Prisma, and Resend, designed to free you from the nitty-gritty of setting up a project, so you can get straight to building your product.<p>No more stress over starting from scratch. No more wasting days on initial codebases. Just your ideas, accelerated with SaaSKits.<p>We look forward to your feedback, and can&#x27;t wait to see what you build with SaaSKits!<p>To quicker launches and big dreams,\nKeyur',
				title: 'Show HN: The fastest way to build your SaaS',
				updated_at: '2024-01-03T06:54:39Z',
				url: 'https://saaskits.dev',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'mayooot-go',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Show HN: Easier Than K8s, Starting GPU Containers',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://github.com/mayooot/gpu-docker-api/blob/main/docs/en.md',
					},
				},
				_tags: ['story', 'author_mayooot-go', 'story_38851457', 'show_hn'],
				author: 'mayooot-go',
				children: [38851463],
				created_at: '2024-01-03T06:50:54Z',
				created_at_i: 1704264654,
				num_comments: 1,
				objectID: '38851457',
				points: 1,
				story_id: 38851457,
				title: 'Show HN: Easier Than K8s, Starting GPU Containers',
				updated_at: '2024-01-03T06:52:54Z',
				url: 'https://github.com/mayooot/gpu-docker-api/blob/main/docs/en.md',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'ukuina',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'Gemini in Reasoning: Unveiling Commonsense in Multimodal Large Language Models',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://arxiv.org/abs/2312.17661',
					},
				},
				_tags: ['story', 'author_ukuina', 'story_38851446'],
				author: 'ukuina',
				created_at: '2024-01-03T06:48:09Z',
				created_at_i: 1704264489,
				num_comments: 0,
				objectID: '38851446',
				points: 1,
				story_id: 38851446,
				title:
					'Gemini in Reasoning: Unveiling Commonsense in Multimodal Large Language Models',
				updated_at: '2024-01-03T06:52:09Z',
				url: 'https://arxiv.org/abs/2312.17661',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'mfiguiere',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'CMA CGM hikes shipping rates by up to 100% between Asia and Mediterranean',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://www.reuters.com/markets/europe/frances-cma-cgm-hikes-shipping-rates-between-asia-mediterranean-2024-01-02/',
					},
				},
				_tags: ['story', 'author_mfiguiere', 'story_38851442'],
				author: 'mfiguiere',
				created_at: '2024-01-03T06:47:27Z',
				created_at_i: 1704264447,
				num_comments: 0,
				objectID: '38851442',
				points: 1,
				story_id: 38851442,
				title:
					'CMA CGM hikes shipping rates by up to 100% between Asia and Mediterranean',
				updated_at: '2024-01-03T06:52:09Z',
				url: 'https://www.reuters.com/markets/europe/frances-cma-cgm-hikes-shipping-rates-between-asia-mediterranean-2024-01-02/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'ZunarJ5',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'Evolution might stop humans from solving climate change, researchers say',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://phys.org/news/2024-01-evolution-humans-climate.html',
					},
				},
				_tags: ['story', 'author_ZunarJ5', 'story_38851423'],
				author: 'ZunarJ5',
				created_at: '2024-01-03T06:42:28Z',
				created_at_i: 1704264148,
				num_comments: 0,
				objectID: '38851423',
				points: 1,
				story_id: 38851423,
				title:
					'Evolution might stop humans from solving climate change, researchers say',
				updated_at: '2024-01-03T06:46:55Z',
				url: 'https://phys.org/news/2024-01-evolution-humans-climate.html',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'ingve',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Textcasting: Applying the Philosophy of Podcasting to Text',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://textcasting.org/',
					},
				},
				_tags: ['story', 'author_ingve', 'story_38851415'],
				author: 'ingve',
				created_at: '2024-01-03T06:41:14Z',
				created_at_i: 1704264074,
				num_comments: 0,
				objectID: '38851415',
				points: 1,
				story_id: 38851415,
				title: 'Textcasting: Applying the Philosophy of Podcasting to Text',
				updated_at: '2024-01-03T06:46:55Z',
				url: 'https://textcasting.org/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'meblum',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Slack Theme Generator',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://slack-themes.vercel.app',
					},
				},
				_tags: ['story', 'author_meblum', 'story_38851411'],
				author: 'meblum',
				created_at: '2024-01-03T06:40:32Z',
				created_at_i: 1704264032,
				num_comments: 0,
				objectID: '38851411',
				points: 1,
				story_id: 38851411,
				title: 'Slack Theme Generator',
				updated_at: '2024-01-03T06:41:39Z',
				url: 'https://slack-themes.vercel.app',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'theshrike79',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'The Game Awards raises an old question: What does indie mean?',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://www.engadget.com/the-game-awards-raises-an-old-question-what-does-indie-mean-205211035.html',
					},
				},
				_tags: ['story', 'author_theshrike79', 'story_38851374'],
				author: 'theshrike79',
				created_at: '2024-01-03T06:31:56Z',
				created_at_i: 1704263516,
				num_comments: 0,
				objectID: '38851374',
				points: 1,
				story_id: 38851374,
				title: 'The Game Awards raises an old question: What does indie mean?',
				updated_at: '2024-01-03T06:36:24Z',
				url: 'https://www.engadget.com/the-game-awards-raises-an-old-question-what-does-indie-mean-205211035.html',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'madmax108',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'The One Billion Row Challenge',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://www.morling.dev/blog/one-billion-row-challenge/',
					},
				},
				_tags: ['story', 'author_madmax108', 'story_38851337'],
				author: 'madmax108',
				created_at: '2024-01-03T06:23:12Z',
				created_at_i: 1704262992,
				num_comments: 0,
				objectID: '38851337',
				points: 2,
				story_id: 38851337,
				title: 'The One Billion Row Challenge',
				updated_at: '2024-01-03T06:39:39Z',
				url: 'https://www.morling.dev/blog/one-billion-row-challenge/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'goindexme',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'Show HN: Go index me – Get indexed by Google and stay indexed',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://goindex.me/#/',
					},
				},
				_tags: ['story', 'author_goindexme', 'story_38851309', 'show_hn'],
				author: 'goindexme',
				created_at: '2024-01-03T06:18:54Z',
				created_at_i: 1704262734,
				num_comments: 0,
				objectID: '38851309',
				points: 9,
				story_id: 38851309,
				title: 'Show HN: Go index me – Get indexed by Google and stay indexed',
				updated_at: '2024-01-03T06:39:39Z',
				url: 'https://goindex.me/#/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'BabelOnTrip',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'BabelOn AI Trip Planner – Launch Upcoming',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://babelontrip.com/',
					},
				},
				_tags: ['story', 'author_BabelOnTrip', 'story_38851299'],
				author: 'BabelOnTrip',
				children: [38851300],
				created_at: '2024-01-03T06:17:08Z',
				created_at_i: 1704262628,
				num_comments: 1,
				objectID: '38851299',
				points: 2,
				story_id: 38851299,
				title: 'BabelOn AI Trip Planner – Launch Upcoming',
				updated_at: '2024-01-03T06:35:09Z',
				url: 'https://babelontrip.com/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'ingve',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'An experimental pip subcommand for the Python Launcher for Unix',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://snarky.ca/an-experimental-pip-subcommand-for-the-python-launcher-for-unix/',
					},
				},
				_tags: ['story', 'author_ingve', 'story_38851277'],
				author: 'ingve',
				created_at: '2024-01-03T06:12:52Z',
				created_at_i: 1704262372,
				num_comments: 0,
				objectID: '38851277',
				points: 2,
				story_id: 38851277,
				title:
					'An experimental pip subcommand for the Python Launcher for Unix',
				updated_at: '2024-01-03T06:37:08Z',
				url: 'https://snarky.ca/an-experimental-pip-subcommand-for-the-python-launcher-for-unix/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'alexpadula',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'A new open-source distributed in-memory and persisted document oriented DBMS',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://github.com/cursusdb/cursusdb',
					},
				},
				_tags: ['story', 'author_alexpadula', 'story_38851251'],
				author: 'alexpadula',
				children: [38851252],
				created_at: '2024-01-03T06:06:37Z',
				created_at_i: 1704261997,
				num_comments: 1,
				objectID: '38851251',
				points: 2,
				story_id: 38851251,
				title:
					'A new open-source distributed in-memory and persisted document oriented DBMS',
				updated_at: '2024-01-03T06:11:24Z',
				url: 'https://github.com/cursusdb/cursusdb',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'r4um',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'A Cap Tradeoff in the Wild',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://decomposition.al/blog/2023/12/31/a-cap-tradeoff-in-the-wild/',
					},
				},
				_tags: ['story', 'author_r4um', 'story_38851250'],
				author: 'r4um',
				created_at: '2024-01-03T06:06:26Z',
				created_at_i: 1704261986,
				num_comments: 0,
				objectID: '38851250',
				points: 1,
				story_id: 38851250,
				title: 'A Cap Tradeoff in the Wild',
				updated_at: '2024-01-03T06:10:09Z',
				url: 'https://decomposition.al/blog/2023/12/31/a-cap-tradeoff-in-the-wild/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'fagnerbrack',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'The Web Can Do What?',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://thewebshowcase.withgoogle.com/',
					},
				},
				_tags: ['story', 'author_fagnerbrack', 'story_38851240'],
				author: 'fagnerbrack',
				created_at: '2024-01-03T06:03:41Z',
				created_at_i: 1704261821,
				num_comments: 0,
				objectID: '38851240',
				points: 2,
				story_id: 38851240,
				title: 'The Web Can Do What?',
				updated_at: '2024-01-03T06:32:24Z',
				url: 'https://thewebshowcase.withgoogle.com/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'nothacking',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'The (Cooley–Tukey) Fast Fourier Transform',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://10maurycy10.github.io/misc/fft/',
					},
				},
				_tags: ['story', 'author_nothacking', 'story_38851234'],
				author: 'nothacking',
				created_at: '2024-01-03T06:02:50Z',
				created_at_i: 1704261770,
				num_comments: 0,
				objectID: '38851234',
				points: 2,
				story_id: 38851234,
				title: 'The (Cooley–Tukey) Fast Fourier Transform',
				updated_at: '2024-01-03T06:09:39Z',
				url: 'https://10maurycy10.github.io/misc/fft/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'gehwartzen',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'Consciousness Is Not Binary',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://www.vcwriting.com/post/consciousness-is-not-binary',
					},
				},
				_tags: ['story', 'author_gehwartzen', 'story_38851206'],
				author: 'gehwartzen',
				created_at: '2024-01-03T05:54:45Z',
				created_at_i: 1704261285,
				num_comments: 0,
				objectID: '38851206',
				points: 3,
				story_id: 38851206,
				title: 'Consciousness Is Not Binary',
				updated_at: '2024-01-03T06:37:38Z',
				url: 'https://www.vcwriting.com/post/consciousness-is-not-binary',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'AntonZ234',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'Why Adding More People Makes a Late Software Project Even Later',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'https://codescene.com/blog/visualize-brooks-law/',
					},
				},
				_tags: ['story', 'author_AntonZ234', 'story_38851201'],
				author: 'AntonZ234',
				created_at: '2024-01-03T05:53:00Z',
				created_at_i: 1704261180,
				num_comments: 0,
				objectID: '38851201',
				points: 2,
				story_id: 38851201,
				title:
					'Why Adding More People Makes a Late Software Project Even Later',
				updated_at: '2024-01-03T06:14:24Z',
				url: 'https://codescene.com/blog/visualize-brooks-law/',
			},
			{
				_highlightResult: {
					author: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'spacedrone808',
					},
					title: {
						matchLevel: 'none',
						matchedWords: [],
						value: 'iPhone 15 Pro Max vs. Nokia PureView 808 [2023 vs. 2012]',
					},
					url: {
						matchLevel: 'none',
						matchedWords: [],
						value:
							'https://trackerninja.codeberg.page/post/iphone-15-pro-max-vs-nokia-pureview-808-2023-vs-2012/',
					},
				},
				_tags: ['story', 'author_spacedrone808', 'story_38851129'],
				author: 'spacedrone808',
				children: [38851130],
				created_at: '2024-01-03T05:39:35Z',
				created_at_i: 1704260375,
				num_comments: 1,
				objectID: '38851129',
				points: 2,
				story_id: 38851129,
				title: 'iPhone 15 Pro Max vs. Nokia PureView 808 [2023 vs. 2012]',
				updated_at: '2024-01-03T06:35:09Z',
				url: 'https://trackerninja.codeberg.page/post/iphone-15-pro-max-vs-nokia-pureview-808-2023-vs-2012/',
			},
		],
		hitsPerPage: 20,
		nbHits: 2705965,
		nbPages: 50,
		page: 0,
		params: 'tags=story&page=0&advancedSyntax=true&analyticsTags=backend',
		processingTimeMS: 1,
		processingTimingsMS: {
			_request: {
				roundTrip: 14,
			},
			total: 1,
		},
		query: '',
		serverTimeMS: 1,
	},
	status: 200,
	statusText: '',
	headers: {
		'content-length': '15997',
		'content-type': 'application/json',
	},
	config: {
		transitional: {
			silentJSONParsing: true,
			forcedJSONParsing: true,
			clarifyTimeoutError: false,
		},
		adapter: ['xhr', 'http'],
		transformRequest: [null],
		transformResponse: [null],
		timeout: 0,
		xsrfCookieName: 'XSRF-TOKEN',
		xsrfHeaderName: 'X-XSRF-TOKEN',
		maxContentLength: -1,
		maxBodyLength: -1,
		env: {},
		headers: {
			Accept: 'application/json, text/plain, */*',
		},
		method: 'get',
		url: 'http://hn.algolia.com/api/v1/search_by_date?tags=story&page=0',
	},
	request: {},
};
